version: "3.4"

services:
  elasticsearch:
    image: fundocker/openshift-elasticsearch:6.6.2
    env_file:
      - ".env"
    ports:
      - "9200:9200"

  app:
    build:
      context: .
      target: production
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    image: "funmooc"
    env_file: ".env"
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend:/app
      - ./data/static:/data/static
      - ./data/media:/data/media
    depends_on:
      - "elasticsearch"
      - "nginx"

  node:
    image: circleci/node:10
    working_dir: /app/src/frontend
    user: "${DOCKER_USER:-1000}"
    volumes:
      - .:/app

  terraform:
    image: hashicorp/terraform:light
    env_file: env.d/aws
    user: "${DOCKER_USER:-1000}"
    working_dir: /app
    volumes:
      - ./src/aws:/app

  nginx:
    image: nginx:1.12.2
    ports:
      - "80:80"
    volumes:
      - ./docker/files/usr/local/etc/nginx/conf.d:/etc/nginx/conf.d:ro